version: appveyor.{build}

image: Ubuntu1804

init:
- sh: sudo apt install --quiet --assume-yes nettle-dev autoconf-archive clang g++ valgrind libc++abi-dev libc++-dev

build_script:
 - sh: >-
    if ./do_quality_checks.sh ; then
      echo all good!
    else
      echo failed.
      for f in *.log; do
        echo ===========================================
        echo file $f:
        cat $f
        echo ===========================================
      done
      exit 1
    fi

# artifacts are not save on failure, so no point in saving them
# for trouble shooting purposes.
artifacts:
- path: '**/*.log'
